version: '3'
services:
  spark:
    image: docker.io/bitnami/spark:3.3
    container_name: databricks_cicd
    hostname: dbconnect
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/databricks_cicd/app/src/
    env_file:
      - databricks.env
      - python.env
      - spark.env
    ports:
      - '8080:8080'
      - '8888:8888'

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no